### ISSUE TITLE
GOT ERROR ABOUT node: bad option: --openssl-legacy-provider 

### ISSUE THREAD

**Issue by katsuxD** [vagabond-systems/jpmc-task-2#7]
Hi JPMC <3 ! 
The server.py is running fine but after install all the necessary packages of node I tried npm start and it gave me that Error. I was looking for a solution from Internet but I could not find a way out! I wonder if does that an error come from my machine? 
![image](https://user-images.githubusercontent.com/52829521/194361923-7b288174-8067-4dd7-ba22-1c498c8230b0.png)

**Comment by katsuxD** [comment]
I did rewrite the code in package.json like
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build --openssl-legacy-provider",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
 Then it ran perfectly :v , I have no idea why
 
![image](https://user-images.githubusercontent.com/52829521/194366917-00ee8d2a-7722-40ff-a15f-994de5b50a83.png)
![image](https://user-images.githubusercontent.com/52829521/194367300-ed405dad-21bf-4cdb-928f-ff582aa3ad71.png)

**Comment by JoshuaR503** [comment]
I had the same error as well. [Found a workaround in this Github thread](https://github.com/coreui/coreui-free-react-admin-template/issues/336#issuecomment-983526097). Instead of removing --openssl-legacy-provider from the start script, I just wrote "start" before the openssl flag resulting in this: 

`"start": "react-scripts start --openssl-legacy-provider"`

**Comment by katsuxD** [comment]
Nice! Thanks @JoshuaR503 
==>
Solution edit like this in your package.json : 
`"start": "react-scripts start --openssl-legacy-provider",`
or
"start": "react-scripts start",
`"build": "react-scripts build --openssl-legacy-provider",`

**Comment by Shubxam** [comment]
@katsuxD @JoshuaR503 appreciate the comments. Had the same issue, but was able to successfully resolve it.
